compiler: xelatex
root_file: paper.tex

#see: https://www.sharelatex.com/github/
#note pdf appears here:
#https://www.sharelatex.com/github/repos/theaok/freedom


# tehre are also those badges that can display in github, juyst by adding readme.md with [![PDF Status](https://www.sharelatex.com/github/repos/theaok/micahEnergy/builds/latest/badge.svg)](https://www.sharelatex.com/github/repos/theaok/micahEnergy/builds/latest/output.pdf)
